  postgres-category:
    image: postgres
    container_name: postgres-category
    environment:
      POSTGRES_USER: roman1
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: budget
    ports:
      - "5435:5432"
    restart: always