version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-transactions
    environment:
      POSTGRES_USER: roman1
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: budget
    ports:
      - "5436:5432"
    restart: always
