postgres-container:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: roman1
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: budget
    ports:
      - "5433:5432"
    restart: always